In [1]:
import numpy as np
import pandas as pd

#### 1. How likely is it that you roll doubles when rolling two dice?

In [ ]:
## outcome possibilities: 1,1; 2,2; 3,3; 4,4; 5,5; 6,6 and there are two trials.  
## Think: the first die is going to be equal to the second die

In [3]:
outcomes = [1, 2, 3, 4, 5, 6]
n_simulations = 10_000

die1 = np.random.choice(outcomes, size=n_simulations)
die2 = np.random.choice(outcomes, size=n_simulations)

In [5]:
rolled_doubles = die1 == die2
rolled_doubles.mean()

0.1735

In [64]:
die1[0:5], die2[0:5]

(array([4, 2, 3, 1, 2]), array([6, 5, 3, 5, 5]))

#### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [ ]:
#8 coins so 8 trials?  and the outcome possibility is heads or tails.  
#i want to know how many times heads > 3

In [8]:
outcomes = [1, 0]  #heads is 1, tails is 0
n_simulations = 10_000
n_trials = 8
flips = np.random.choice(outcomes, size=(n_simulations, n_trials))
flips[0:5]

array([[0, 0, 0, 0, 1, 1, 1, 0],
       [1, 0, 1, 1, 1, 0, 0, 1],
       [0, 1, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 1, 0]])

In [9]:
sum_of_flips = flips.sum(axis=1)
sum_of_flips[0:5]

array([3, 5, 3, 1, 3])

In [10]:
(sum_of_flips == 3).mean()

0.2171

In [66]:
(sum_of_flips > 3).mean()

0.632

#### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [15]:
#3:1 or w,w,w,d

#outcomes = ["WebDev", "Data"]
outcomes = [0, 1]

billboard_select = np.random.choice(outcomes, size=(10_000, 2), p=[0.75, 0.25])

num_of_select = billboard_select.sum(axis=1)
(num_of_select == 2).mean()


0.0663

#### 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [ ]:
#1.5 up to 4.5 poptarts per day, avg of 3. 
#after 5 days, how likely is it that the sum of poptarts is > 1?

In [67]:

poptart = np.random.normal(loc = 3, scale = 1.5, size = (10_000, 5))

number_of_poptarts = poptart.sum(axis=1)
(number_of_poptarts < 17).mean()

0.7278

In [68]:
poptart = np.random.uniform(low = 1.5, high = 4.5, size = (10_000, 5))

number_of_poptarts = poptart.sum(axis=1)
(number_of_poptarts < 17).mean()

0.848

#### 5. Compare Heights

    Men have an average height of 178 cm and standard deviation of 8cm.
    Women have a mean of 170, sd = 6cm.
    Since you have means and standard deviations, you can use np.random.normal to generate observations.
    If a man and woman are chosen at random, P(woman taller than man)?

In [21]:
m_height = np.random.normal(loc = 178, scale = 8, size = (10_000, 1))
w_height = np.random.normal(loc = 170, scale = 6, size = (10_000, 1))

(m_height < w_height).mean()

0.2162

In [24]:
m_height[0:5] , w_height[0:5]

(array([[177.76659709],
        [168.79765477],
        [173.79756541],
        [168.15663188],
        [187.96529034]]),
 array([[157.53911845],
        [179.67961223],
        [170.14776935],
        [164.29887447],
        [171.54170309]]))

#### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

     What is the probability that we observe an installation issue within the first 150 students that download anaconda?

    How likely is it that 450 students all download anaconda without an issue?

In [69]:
outcomes = [0, 1]
n_downloads = 50
#0 is pass, and 1 is fail
download = np.random.choice(outcomes, size = (10_000 , n_downloads), p = (.996, .004))

df = pd.DataFrame(download)

df["c_downloads"] = df.sum(axis=1)
(df.c_downloads == 0).mean()

0.8169

In [71]:
df.c_downloads.value_counts()

0    8169
1    1661
2     160
3       9
4       1
Name: c_downloads, dtype: int64

In [32]:
outcomes = [0, 1]
n_downloads = 100
#0 is pass, and 1 is fail
download = np.random.choice(outcomes, size = (10_000 , n_downloads), p = (.996, .004))

c_downloads = download.sum(axis=1)
(c_downloads == 0).mean()

0.6615

In [33]:
outcomes = [0, 1]
n_downloads = 150
#0 is pass, and 1 is fail
download = np.random.choice(outcomes, size = (10_000 , n_downloads), p = (.996, .004))

c_downloads = download.sum(axis=1)
(c_downloads == 0).mean()

0.5427

In [34]:
outcomes = [0, 1]
n_downloads = 450
#0 is pass, and 1 is fail
download = np.random.choice(outcomes, size = (10_000 , n_downloads), p = (.996, .004))

c_downloads = download.sum(axis=1)
(c_downloads == 0).mean()

0.1667

#### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

    How likely is it that a food truck will show up sometime this week?

In [36]:
# at least one, so there could be zero to many.  this sounds like its indicating the type of distribution.  0 or >0
# no, on second thought the choice is there is a truck(s), or there is not.
#the outcomes are truck(s) or no truck.

outcomes = [0,1]
n_days = 3
#0 is no truck, 1 is a truck(s)
truck_in_park = np.random.choice(outcomes, size = (10_000, n_days), p = (.3, .7))

truck_sighting = truck_in_park.sum(axis=1)
(truck_sighting == 0).mean()

0.0301

In [38]:
outcomes = [0,1]
n_days = 4
#0 is no truck, 1 is a truck(s)
truck_in_park = np.random.choice(outcomes, size = (10_000, n_days), p = (.3, .7))

truck_sighting = truck_in_park.sum(axis=1)
(truck_sighting > 0).mean()

0.9918

#### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [39]:
#1/365 chance; #of people is the number of columns, a match is a yes

outcomes = [0,1]
#0 is not a bday match, 1 is a bday match
n_people = 23
bdays = np.random.choice(outcomes, size = (10_000, n_people), p = (.997, .003))

bday_match = bdays.sum(axis=1)
(bday_match == 1).mean()
                              
                              

0.0665

In [40]:
outcomes = [0,1]
#0 is not a bday match, 1 is a bday match
n_people = 20
bdays = np.random.choice(outcomes, size = (10_000, n_people), p = (.997, .003))

bday_match = bdays.sum(axis=1)
(bday_match == 1).mean()

0.0555

In [41]:
outcomes = [0,1]
#0 is not a bday match, 1 is a bday match
n_people = 40
bdays = np.random.choice(outcomes, size = (10_000, n_people), p = (.997, .003))

bday_match = bdays.sum(axis=1)
(bday_match == 1).mean()

0.1076

In [45]:
n_people = 5
bdays = np.random.choice(outcomes, size = (10_000, n_people), p = (.997, .003))
bdays[0:5]

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [46]:
n_simulations = 1_000_000
n_trials = 23
same_birthday = np.random.randint(low = 1,high = 366 , size=(n_simulations,n_trials),dtype = int)

In [47]:
same_birthday[0:5]

array([[317, 198, 256, 258, 160, 228,  99, 230, 155, 326,  37, 102, 322,
        280,  34, 199, 210, 102,   3, 263, 328, 247, 237],
       [268, 299, 234, 153, 293, 157, 158, 282, 150, 112, 184, 321, 160,
        350, 350, 175, 182,   3,  33, 220,  41, 339, 160],
       [ 45, 130, 319, 206,  93, 204, 278,  56,  70, 148,  88, 145,  84,
         80, 328,   9, 306, 220, 219, 225, 329, 301, 345],
       [221, 331,  88,  21,  94, 187, 230,  61, 245, 308, 229,  56, 304,
        123, 333, 265, 244, 120, 352, 322,  60, 145, 295],
       [ 62, 159, 125,   4, 230, 282, 295,  86,  98, 332, 335, 199, 196,
         71, 227, 262, 272, 144, 287, 269, 172,  92, 227]])

In [54]:
#here is something I found setting up a df and function to determine the probability:
import random
import datetime

birthdays = pd.DataFrame(np.empty([365,2]), columns = ['k','probability'], index = range(1,366))
birthdays['k'] = birthdays.index

In [49]:
def probability_of_shared_bday(k):
    end_point = 366 - k
    ratio = 1
    for i in range(end_point, 366):
        ratio *= i / 365
    probability_of_no_match = (1 - ratio)
    return probability_of_no_match

In [50]:
probability_of_shared_bday(23)

0.5072972343239853

In [51]:
probability_of_shared_bday(40)

0.891231809817949

In [59]:
def proportion_shared_bdays(k):
    parties_with_shared_bday = 0
    for i in range(1000):
        random_indexes = random.sample(range(1,341),k)
        party = birthdays['k'][random_indexes]
        if sum(party.duplicated())>0:
            parties_with_shared_bday +=1
    proportion_shared_bdays = parties_with_shared_bday/1000
    return proportion_shared_bdays

In [60]:
proportion_shared_bdays(23)

0.0

In [62]:
probability_of_shared_bday(100)

0.9999996927510721